<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <Import Project="..\AOT.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>false</IsTestProject>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Nerdbank.MessagePack" />
    <TrimmerRootAssembly Include="Nerdbank.MessagePack.AspNetCoreMvcFormatter" />
    <TrimmerRootAssembly Include="Nerdbank.MessagePack.Godot" />
    <TrimmerRootAssembly Include="Nerdbank.MessagePack.SignalR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nerdbank.MessagePack\Nerdbank.MessagePack.csproj" />
    <ProjectReference Include="..\..\src\Nerdbank.MessagePack.AspNetCoreMvcFormatter\Nerdbank.MessagePack.AspNetCoreMvcFormatter.csproj" />
    <ProjectReference Include="..\..\src\Nerdbank.MessagePack.Godot\Nerdbank.MessagePack.Godot.csproj" />
    <ProjectReference Include="..\..\src\Nerdbank.MessagePack.SignalR\Nerdbank.MessagePack.SignalR.csproj" />
  </ItemGroup>
</Project>
