<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Nerdbank.MessagePack.Godot\Nerdbank.MessagePack.Godot.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>
</Project>
